#!/usr/bin/env bash
# Write ~/.ssh/config.d/trimurti from inventory.csv so that `ssh <name>` works
# for every machine, and make ~/.ssh/config include it. Safe to rerun; edit
# inventory.csv, not the generated file.
# shellcheck disable=SC2034  # every inventory column is read, not every one is used
set -eu
# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"

CFG_DIR="$HOME/.ssh/config.d"; CFG="$CFG_DIR/trimurti"; MAIN="$HOME/.ssh/config"
umask 077; mkdir -p "$CFG_DIR"; touch "$MAIN"

{
  printf '# generated by ops/network/scripts/ssh-config-gen.sh on %s -- edit inventory.csv, not this file\n' "$(date +%F)"
  while IFS=, read -r name ip mac os user role port trimurti notes; do
    [ -n "$name" ] || continue
    printf '\nHost %s\n  HostName %s\n  User %s\n  Port %s\n  IdentityFile %s\n  IdentitiesOnly yes\n  ServerAliveInterval 30\n  ServerAliveCountMax 3\n' \
      "$name" "${ip:-$name}" "$user" "${port:-22}" "$KEY_FILE"
  done <<< "$(select_hosts)"
} > "$CFG"

if ! grep -qs '^Include config.d/\*' "$MAIN"; then
  tmp="$(mktemp)"; { printf 'Include config.d/*\n\n'; cat "$MAIN"; } > "$tmp"; mv "$tmp" "$MAIN"; chmod 600 "$MAIN"
fi
ok "wrote $CFG ($(grep -c '^Host ' "$CFG") hosts); 'Include config.d/*' is in $MAIN"
log "try:  ssh <name>   for any name in inventory.csv"
