#!/usr/bin/env bash
# Write ~/.ssh/config.d/trimurti from inventory.csv so that `ssh <name>` works
# for every machine, and make ~/.ssh/config include it. Safe to rerun; edit
# inventory.csv, not the generated file.
#
# Usage: ssh-config-gen.sh
# One Host block per row that has a user and an ssh_port. Rows with a blank
# ssh_port (no SSH) and the router get none. The new file is checked with
# `ssh -G` first; if ssh rejects it, the old file stays and this exits 1.
# shellcheck disable=SC2034  # every inventory column is read, not every one is used
set -eu
# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"
case "${1:-}" in -h|--help) usage 0 ;; "") ;; *) bad_usage "unexpected argument: $1" ;; esac
check_inventory

CFG_DIR="$HOME/.ssh/config.d"; CFG="$CFG_DIR/trimurti"; MAIN="$HOME/.ssh/config"
umask 077; mkdir -p "$CFG_DIR"; touch "$MAIN"
# ~ keeps a path with spaces short, and works for Git Bash's ssh and Windows ssh.exe alike
key="$KEY_FILE"
# shellcheck disable=SC2088  # the ~ is for ssh to expand
case "$key" in "$HOME"/*) key="~/${key#"$HOME"/}" ;; esac
tmp="$(mktemp "$CFG_DIR/.trimurti.XXXXXX")"; trap 'rm -f "$tmp"' EXIT

NAMES=""
{
  printf '# generated by ops/network/scripts/ssh-config-gen.sh on %s -- edit inventory.csv, not this file\n' "$(date +%F)"
  while IFS=, read -r name ip mac os user role port trimurti notes; do
    [ -n "$name" ] || continue
    why="$(ssh_skip_reason "$user" "$port")"
    if [ -z "$why" ]; then
      case "$user" in *'"'*) why="user '$user' has a double quote" ;; esac
      case "$ip" in *[!0-9A-Za-z.:-]*) why="ip '$ip' is not an address" ;; esac
    fi
    if [ -n "$why" ]; then warn "$name: no Host block, $why" >&2; continue; fi
    printf '\nHost %s\n  HostName %s\n  User "%s"\n  Port %s\n  IdentityFile "%s"\n  IdentitiesOnly yes\n  ServerAliveInterval 30\n  ServerAliveCountMax 3\n' \
      "$name" "${ip:-$name}" "$user" "$port" "$key"
    # Apple's ssh keeps the key's passphrase in the Keychain across reboots
    if [ "$(local_os)" = macos ]; then printf '  IgnoreUnknown UseKeychain\n  UseKeychain yes\n  AddKeysToAgent yes\n'; fi
    NAMES="$NAMES $name"
  done <<< "$(select_hosts all)"
} > "$tmp"

# A bad line in an included file stops every ssh on this machine, so check before replacing.
if ssh -G -F /dev/null localhost >/dev/null 2>&1; then
  for name in $NAMES; do
    if ! err="$(ssh -G -F "$tmp" "$name" 2>&1 >/dev/null)"; then
      die "ssh rejects the generated block for $name, so $CFG was left as it was: $(printf '%s\n' "$err" | head -1)"
    fi
  done
fi
mv "$tmp" "$CFG"; chmod 600 "$CFG"

if ! grep -qs '^Include config.d/\*' "$MAIN"; then
  tmp="$(mktemp)"; { printf 'Include config.d/*\n\n'; cat "$MAIN"; } > "$tmp"; mv "$tmp" "$MAIN"; chmod 600 "$MAIN"
fi
ok "wrote $CFG ($(grep -c '^Host ' "$CFG") hosts); 'Include config.d/*' is in $MAIN"
log "try:  ssh <name>   for any name in inventory.csv"
