<#
Windows admin-machine version of ssh-config-gen.sh: writes
$HOME\.ssh\config.d\trimurti from inventory.csv and includes it from
$HOME\.ssh\config, so `ssh <name>` works from PowerShell. Windows' OpenSSH
client (8.1+) honours Include. Safe to rerun.

Usage: powershell -ExecutionPolicy Bypass -File scripts\ssh-config-gen.ps1 [-KeyFile C:\Users\me\.ssh\id_ed25519_trimurti]
#>
param([string]$KeyFile = (Join-Path $HOME '.ssh\id_ed25519_trimurti'))
$ErrorActionPreference = 'Stop'

$OpsDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$rows = Get-Content (Join-Path $OpsDir 'inventory.csv') | Where-Object { $_ -notmatch '^\s*#' -and $_.Trim() } | ConvertFrom-Csv
$dir  = Join-Path $HOME '.ssh\config.d'; New-Item -ItemType Directory -Force -Path $dir | Out-Null
$cfg  = Join-Path $dir 'trimurti'
$main = Join-Path $HOME '.ssh\config'

$lines = @("# generated by ops/network/scripts/ssh-config-gen.ps1 on $(Get-Date -Format yyyy-MM-dd) -- edit inventory.csv, not this file")
$n = 0
foreach ($r in $rows) {
  if (-not $r.name -or $r.role -eq 'router') { continue }
  $hostName = if ($r.ip) { $r.ip } else { $r.name }
  $port     = if ($r.ssh_port) { $r.ssh_port } else { 22 }
  $lines += '', "Host $($r.name)", "  HostName $hostName", "  User $($r.user)", "  Port $port",
            "  IdentityFile $KeyFile", '  IdentitiesOnly yes', '  ServerAliveInterval 30', '  ServerAliveCountMax 3'
  $n++
}
Set-Content -Path $cfg -Value $lines -Encoding ascii
if (-not (Test-Path $main)) { New-Item -ItemType File -Path $main -Force | Out-Null }
if (-not (Select-String -Path $main -Pattern '^Include config\.d/\*' -Quiet)) {
  Set-Content -Path $main -Value (@('Include config.d/*', '') + @(Get-Content $main)) -Encoding ascii
}
Write-Host "wrote $cfg ($n hosts); 'Include config.d/*' is in $main. Try:  ssh <name>"
